### ISSUE TITLE
Django 4 and django-redshift-backend 3 help to run migrations locally

### ISSUE THREAD

**Issue by fizyk** [jazzband/django-redshift-backend#101]
Subject: Django 4 and django-redshift-backend 3 migration help

### Problem
- I'm attempting to migrate our redshift app to Django 4 and django-redshift-backend 3 however I stumbled on this weird issue:
We migrate database in tests, but Django 4 dropped support for Postgres 9.6, which results in the failed migrations on local/test environments either due to `column c.relispartition does not exist when using PostgreSQL engine or `CREATE TABLE "django_migrations" ("id" bigint identity(1, 1)...` when attempting to migrate using the django-redshift-backend engine locally.

#### Procedure to reproduce the problem
Can think of anything else at this time than to actually run the migrations on the test database PostgreSQL

#### Error logs / results
Those two mentioned in the Problem section

#### Expected results
Django migrates both locally on Postgres and redshift.

### Environment info
- OS: Linux
- Python version: 3.9.2
- Django version: 4.0.4
- Django-Redshift-Backend version: 3.0.0

### Side note
this is kind of followup to #100, just trying to adjust our local development environment a bit.

**Comment by shimizukawa** [comment]
@fizyk Please let me know what are the DATABASES settings in settings.py?
Since django-redshift-backend 3.0 should not reference `c.relispartition`.

**Comment by fizyk** [comment]
@shimizukawa engine is set to redshift, locally is Postgres. I think I got confused a bit and set up to redshift locally... 🤔 

Surprisingly at the moment, everything works as long as I set up local PostgreSQL to any django-supported version... 

Hmmm... what's your approach to local development? Which PostgreSQL version do you use to develop Redshift based apps locally? And why Django-redshift-backend's test uses 9.6? You don't run migrations against local Postgres here, do you?
