### ISSUE TITLE
I can not make migration file

### ISSUE THREAD

**Issue by soseki-angfa** [jazzband/django-redshift-backend#117]
Subject: django 4.0/python 3.8

### Problem
I can not create first migration.
When I looked at error logs, It seems to me that django dose not recognise django-redshift-backend.

I have database setting as following.
![image](https://github.com/jazzband/django-redshift-backend/assets/106799197/8c96695b-3021-4ec2-930e-85f3ec93a56a)

#### Procedure to reproduce the problem
python3 manage.py makemigrations my_project

#### Error logs / results
```
django.core.exceptions.ImproperlyConfigured: 'django_redshift_backend' isn't an available database backend or couldn't be imported. Check the above exception. To use one of the built-in backends, use 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
```

#### Expected results
Migration is created.

### Environment info
- OS: Amazon Linux 2
- Python version: 3.8
- Django version: 4.0
- Django-Redshift-Backend version:3.0 

Do you have any suggestion for this?

Regards.

**Comment by shimizukawa** [comment]
@soseki-angfa I'm sorry for the late reply.
Please check to see if the `django-redshift-backend` installation was successful.

```
$ pip show django-redshift-backend
...(information are shown if it is installed)...

$ python
Python 3.10.14 (main, May 14 2024, 08:39:53) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import django_redshift_backend
>>> django_redshift_backend.__version__
'3.0.0' 
```

I'm closing this issue, but if the issue still hasn't been resolved, please reopen it.

**Comment by soseki-angfa** [comment]
Thanks
