### ISSUE TITLE
Migrating to Jazzband

### ISSUE THREAD

**Issue by shimizukawa** [jazzband/django-redshift-backend#51]
According to what we agreed before on #30, I will start migrating to Jazzband.

**Comment by shimizukawa** [comment]
Preparing:

- Done on #30

Steps.

1. Transferring this repository into https://github.com/jazzband .
2. Treat CI & ReadTheDocs to new repository URL.
3. Resolve rest of issues for milestone 1.0
4. Release 1.0

**Comment by shimizukawa** [comment]
`jazzband` user on PyPI is now become a maintainer of django-redshift-backend project on PyPI.
https://pypi.org/project/django-redshift-backend/

**Comment by shimizukawa** [comment]
Add `jazzband-bot` as maintainer to the Read the Docs project
https://readthedocs.org/dashboard/django-redshift-backend/users/

**Comment by shimizukawa** [comment]
Hum, Jazzband ToDo ticket is automatically created
https://github.com/jazzband/roadies/issues/107#todos

**Comment by Surgo** [comment]
Thank you for your work :)

**Comment by shimizukawa** [comment]
followed https://jazzband.co/about/releases setup

* Adopt to setuptools_scm https://github.com/jazzband/django-redshift-backend/commit/775c58d30f8e60f3d24bfb21af93a7cfb755bd1b
* request "lead" member https://github.com/jazzband/roadies/issues/113
* request setup "pypi" auto releasing https://github.com/jazzband/roadies/issues/114

**Comment by shimizukawa** [comment]
using tox-travis that recommended by jazzband: https://github.com/jazzband/django-redshift-backend/pull/52

**Comment by shimizukawa** [comment]
#52 is merged. 
I'm going to release 1.0.0a1 as a bot workflow testing

**Comment by shimizukawa** [comment]
I tagged `1.0.0a2` (a1 is already exist).
https://github.com/jazzband/django-redshift-backend/releases/tag/1.0.0a2

**Comment by Surgo** [comment]
@shimizukawa I got a mail about <https://jazzband.co/projects/django-redshift-backend>
Does this mean we have to do some actions?

**Comment by shimizukawa** [comment]
Travis didn't deploy 1.0.0a2..
I will make a new empty commit.

**Comment by shimizukawa** [comment]
hum...  I don't understand what happen.
As @Surgo mentioned, some trouble was occurred
> HTTPError: 400 Client Error: File already exists. for url: https://jazzband.co/projects/django-redshift-backend/upload

refs: https://travis-ci.org/jazzband/django-redshift-backend/jobs/485747325#L390

**Comment by shimizukawa** [comment]
Sorry, I misunderstood a meaning what  Surgo mentioned.

Finally we got a 1.0.0a2 release on PyPI!
https://pypi.org/project/django-redshift-backend/1.0.0a2/

**Comment by shimizukawa** [comment]
@Surgo can you please try 1.0.0a2 release?
If it's confirmed, I'm going to release 1.0.0 with no changes.

**Comment by jezdez** [comment]
Congratulations to your first release! 🎉

**Comment by Surgo** [comment]
## Install

```
pip install django-redshift-backend==1.0.0a2
Collecting django-redshift-backend==1.0.0a2
  Downloading https://files.pythonhosted.org/packages/56/e6/45df199542d6e46316a96a6155d634868569542efdfbfb38897297478ad6/django_redshift_backend-1.0.0a2-py2.py3-none-any.whl
...
Successfully installed django-redshift-backend-1.0.0a2
```

## Import

```
>>> from django_redshift_backend.base import DatabaseWrapper
>>>
```

## Use 

It's works fine :) @shimizukawa

**Comment by shimizukawa** [comment]
🎉 
Finally! "Migrating to Jazzband" has been completed! Thanks for your cooperation!

And I'm going to release 1.0.0 soon.

**Comment by Surgo** [comment]
@shimizukawa Thank you for your works :)
