### ISSUE TITLE
No SQL is generated when changing a field from NOT NULL to NULL

### ISSUE THREAD

**Issue by msmolens** [jazzband/django-redshift-backend#63]
### Problem
No SQL is generated for a migration that changes a field from NOT NULL to NULL.

#### Procedure to reproduce the problem
A Django model is created with a non-nullable field:
```python
result = models.CharField(max_length=255, null=False)
```
which creates a migration like:
```python
migrations.CreateModel(
    name='MyModel',
    fields=[
        ('result', models.CharField(max_length=255)),
    ],
    ...
```
The field is then changed to be nullable:
```python
result = models.CharField(max_length=255, null=True)
```
which creates a migration like:
```python
migrations.AlterField(
    model_name='mymodel',
    name='result',
    field=models.CharField(max_length=255, null=True),
),
```
After applying this migration, the column in Redshift is unexpectedly still NOT NULL. This happens because no SQL was generated for the AlterField operation:
```
$ python manage.py sqlmigrate myapp mymigration
BEGIN;
--
-- Alter field result on mymodel
--
COMMIT;
```

#### Expected results
An AlterField operation that changes a non-nullable field to nullable should generate SQL that changes the nullability of the column.

### Environment info
- OS: Linux
- Python version: 3.7.4
- Django version: 2.1.14
- Django-Redshift-Backend version: 1.1.0

**Comment by shimizukawa** [comment]
Thanks for your reporting.
(Is there anyone who can fix it?)

**Comment by shimizukawa** [comment]
fixed by https://github.com/jazzband/django-redshift-backend/pull/97.

**Comment by shimizukawa** [comment]
It has been released https://pypi.org/project/django-redshift-backend/3.0.0/
