### ISSUE TITLE
Very long TravisCI builds

### ISSUE THREAD

**Issue by browniebroke** [jazzband/django-redshift-backend#70]
### Problem

I recently submitted a couple of pull requests to fix some issues I was having, and noticed that the TravisCI build was very slow, sometimes taking several hours to just start and a couple more to finish.

This seems caused by Travis [recent pricing change](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) which limit open source to 1000 minutes, I suppose jazzband is hitting this quota very quickly.

Since this is not an issue specific to `django-redshift-backend`, I first tried to reach out on IRC, but I'm not sure if my message went through....

#### Procedure to reproduce the problem

Example of pull request: https://github.com/jazzband/django-redshift-backend/pull/68
Build for the first commit: https://travis-ci.org/github/jazzband/django-redshift-backend/builds/741443844

PR submitted on 4th Nov 5:06pm GMT
Build started 5th Nov 1:32am GMT
Build finished 5th Nov 3:30am GMT

#### Suggested Solution

I think it's easy to agree that this is not sustainable for contributors and even less for maintainers. I'd be happy to help, but first I'd like to confirm the CI that the Jazzband org wants to use. I assume Github actions is the easiest these days as it doesn't require maintainers to grant anything and it has a generous free allowance.

The only part I'm seeing where we would need a maintainer to step in is to add the PyPI token to the repository secrets to keep release automation working.

FYI @jezdez as roadie and @shimizukawa as recent active maintainer...

**Comment by jezdez** [comment]
Yeah, GitHub actions is the way to go here and I plan to spend time this year to work on this. E.g. prettytable has a good setup on GA already: https://github.com/jazzband/prettytable/blob/master/.github/workflows/test.yml

**Comment by jezdez** [comment]
Just wanted to say, if you have time to work on this, this would be incredibly useful!

**Comment by browniebroke** [comment]
Ok. I tried to stay close to the current Travis config: https://github.com/jazzband/django-redshift-backend/pull/71

I can't test the final step to publish the package, but the rest works. The status check are not showing up in the pull request, I'm guessing it's due to the workflow not being in the main branch yet.

I'm open to suggestions to make the config less verbose. I'm planning to fix up #68 once it's merged.

**Comment by browniebroke** [comment]
Fixed now. CI was moved to GH actions.
